fname = input("Enter First  Name: ")
lastname = input("Enter Last Name: ")
middlename = input("Enter Middle Name: ")
birthday = input("Enter Birthday: ")
gender = input("Enter Gender: ")
address = input("Enter Address: ")
course = input("Enter Course: ")
yearlevel = input("Enter Year level: ")

print("My name is:", fname)
print("My Last name is:", lastname)
print("My Midlle name  is:", middlename)
print("My Birthday is:", birthday)
print("My Gender is:", gender)
print("My Address is:", address)
print("My Course is:", course)
print("My Year level is:", yearlevel)